import logo from './logo.svg'
import phone_icon from './phone_icon.svg'
import email from './email.svg'
import savat from './cart.svg'
import katalog from './katalog.svg'
import like from './like.svg'
import user from './user.svg'
import lokatsiya from './lokatsiya.svg'
import telegram from './telegram.svg'
import instagram from './instagram.svg'
import facebook from './facebook.svg'
import swapper1 from './swapper-1.jpg'
import swapper2 from './swapper-2.png'
import swapper3 from './swapper-3.jpg'
import swapper4 from './swapper-4.jpg'
import swapper5 from './swapper-5.jpg'
import card1 from './card1.png'
import card2 from './card2.png'
import card3 from './card3.png'
import card4 from './card4.png'
import card5 from './card5.png'
import card6 from './card6.png'
import product1 from './product1.svg'
import product2 from './product2.png'
import product3 from './product3.png'
import product4 from './product4.png'
import nextIcon from './next.svg'
import puma from './puma-icon.svg'
import nike from './nike.svg'
import adidas from './adidas-icon.svg'
import reebok from './reebok.svg'
import icon2 from './icon-firma.svg'
import taksi from './yandex_taksi.svg'
import check from './check.svg'
import aksiya from './aksiya.svg'
import check2 from './tovar_check.svg'
import sport_img from './sport-img.svg'
import eye from './eye.svg'
import calendar from './calender.svg'
import action from "./action.svg"
import board from "./board.svg"
import list from "./list.svg"
import search from "./search.svg"
import menu from "./menu.svg"
import share from "./share.svg"
import print from "./print.svg"
import delete_icon from "./delete_icon.svg"
import payme from "./payme_icon.svg"
import click from "./click_icon.svg"
import shopping_bag from "./shopping_bag.png"


export {logo, phone_icon, email, savat, user, like, katalog, lokatsiya, telegram, instagram, facebook, swapper1, swapper2, swapper3, swapper4, swapper5, card1,card2,card3, card4, card5,card6, product1, product2,product3,product4, nextIcon, puma,nike, adidas, reebok, icon2, taksi,check,check2, aksiya, sport_img, eye, calendar, action, board, list, search, menu, share, delete_icon , print, payme, click, shopping_bag}